name: 'sf_crime_warehouse'
version: '1.0.0'
profile: 'sf_crime'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  sf_crime_warehouse:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      dimensions:
        +materialized: table
      facts:
        +materialized: table
      analytics:
        +materialized: table