version: 2

models:
  - name: stg_crime_incidents
    columns:
      - name: incident_id
        tests:
          - not_null
      - name: incident_code
        tests:
          - not_null

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - incident_id
            - incident_code