models:
  - name: dim_date
    columns:
      - name: date_id
        tests: [unique, not_null]
  - name: dim_offense_category
    columns:
      - name: offense_category_id
        tests: [unique, not_null]
  - name: dim_geo
    columns:
      - name: geo_id
        tests: [unique, not_null]
  - name: dim_time
    columns:
      - name: time_id
        tests: [unique, not_null]
  - name: dim_resolution
    columns:
      - name: resolution_id
        tests: [unique, not_null]
